# Import libraries

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

#Import Datasets
- WIC_formula_vendors.xlsx
- FoodAccessResearchAtlasData2019.xlsx

1) Import the WIC Formula Vendors Excel File

In [2]:
wic_harris_cnty = pd.read_excel('/content/drive/MyDrive/medschool project/WIC_formula_vendors.xlsx')
wic_harris_cnty = wic_harris_cnty[wic_harris_cnty['County'] == 'HARRIS']
wic_harris_cnty = wic_harris_cnty[['County', 'Store Name',
                 'Store Address', 'City', 'Zip',
                 'Tract', 'LILA 1 and 10',
                 'LILA .5 and 10']]
wic_harris_cnty[['Tract', 'Zip']] = wic_harris_cnty[['Tract', 'Zip']].astype(str)
wic_harris_cnty['Tract'] = wic_harris_cnty['Tract'].str[:-2]
wic_harris_cnty = wic_harris_cnty.rename(columns = {'Tract':'CensusTract'})
wic_harris_cnty = wic_harris_cnty[(wic_harris_cnty['Store Name'] != 'ANGEL MEDICAL SUPPLY LLC')]
wic_harris_cnty = wic_harris_cnty[(wic_harris_cnty['Store Name'] != 'FOOD CITY')]

2) Import the Food Atlas Dataset

In [3]:
df_food_atlas = pd.read_excel('/content/drive/MyDrive/medschool project/FoodAccessResearchAtlasData2019.xlsx',
                              sheet_name = 'Food Access Research Atlas')
# Filter the data
df_food_atlas = df_food_atlas[(df_food_atlas['County'] == 'Harris County') &(df_food_atlas['State'] == 'Texas')]
df_food_atlas['CensusTract'] = df_food_atlas['CensusTract'].astype(str)
df_food_atlas

,CensusTract,State,County,Urban,Pop2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
63453,48201100000,Texas,Harris County,1,4690,1737,0,2407.0,51.321962,0,...,159.0,2669.0,1068.0,137.0,1.0,25.0,790.0,1070.0,368.0,157.0
63454,48201210100,Texas,Harris County,1,9652,72,1,9551.0,98.953585,0,...,49.0,4515.0,4903.0,61.0,0.0,3.0,170.0,1788.0,0.0,0.0
63455,48201210400,Texas,Harris County,1,5328,1593,0,257.0,4.823574,0,...,455.0,2617.0,931.0,26.0,4.0,43.0,1707.0,4025.0,353.0,377.0
63456,48201210500,Texas,Harris County,1,4882,1504,0,61.0,1.249488,0,...,523.0,2532.0,558.0,11.0,0.0,30.0,1751.0,4096.0,234.0,339.0
63457,48201210600,Texas,Harris County,1,5497,2037,0,0.0,0.000000,0,...,725.0,3832.0,117.0,41.0,1.0,53.0,1453.0,4378.0,154.0,181.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64234,48201555701,Texas,Harris County,1,7064,2167,0,0.0,0.000000,0,...,270.0,5720.0,528.0,296.0,6.0,28.0,486.0,1245.0,0.0,61.0
64235,48201555702,Texas,Harris County,1,9389,2848,0,0.0,0.000000,0,...,496.0,7897.0,544.0,438.0,4.0,41.0,465.0,1169.0,70.0,91.0
64236,48201556000,Texas,Harris County,0,6462,1997,0,144.0,2.228412,0,...,454.0,4241.0,816.0,45.0,6.0,71.0,1283.0,2509.0,105.0,259.0
64237,48201980000,Texas,Harris County,1,33,15,0,0.0,0.000000,1,...,3.0,20.0,12.0,0.0,0.0,0.0,1.0,9.0,0.0,3.0
64238,48201980100,Texas,Harris County,1,603,224,0,0.0,0.000000,1,...,8.0,130.0,374.0,8.0,4.0,2.0,85.0,157.0,11.0,31.0

In [10]:
LILATracts_1And10_is1 = df_food_atlas[['CensusTract',  'LILATracts_1And10']][df_food_atlas['LILATracts_1And10'] == 1]
print(f'There are # number of instances ', len(LILATracts_1And10_is1), 'where LILATracts_1And10 = 1 in the dataset')

LA1and10_is1_L1_is0 = df_food_atlas[['CensusTract',  'LA1and10','LowIncomeTracts']][(df_food_atlas['LA1and10'] == 1) &\
                                                                              (df_food_atlas['LowIncomeTracts'] == 0)]
print(f'There are # number of instances ', len(LA1and10_is1_L1_is0), 'where LA1and10 = 1 and LowIncomeTracts = 0 in the dataset')

LA1and10_is0_L1_is1 = df_food_atlas[['CensusTract',  'LA1and10', 'LowIncomeTracts']][(df_food_atlas['LA1and10'] == 0) &\
                                                                              (df_food_atlas['LowIncomeTracts'] == 1)]
print(f'There are # number of instances ', len(LA1and10_is0_L1_is1), 'where LA1and10 = 0 and LowIncomeTracts = 1 in the dataset')

LA1and10_is0_L1_is0 = df_food_atlas[['CensusTract',  'LA1and10', 'LowIncomeTracts']][(df_food_atlas['LA1and10'] == 0) &\
                                                                              (df_food_atlas['LowIncomeTracts'] == 0)]
print(f'There are # number of instances ', len(LA1and10_is0_L1_is0), 'where LA1and10 = 0 and LowIncomeTracts = 0 in the dataset')

There are # number of instances  120 where LILATracts_1And10 = 1 in the dataset
There are # number of instances  152 where LA1and10 = 1 and LowIncomeTracts = 0 in the dataset
There are # number of instances  296 where LA1and10 = 0 and LowIncomeTracts = 1 in the dataset
There are # number of instances  218 where LA1and10 = 0 and LowIncomeTracts = 0 in the dataset

Check if census tract in each data exists in WIC, if so, add 1 in a new column called exists in WIC for each dataset

# LA1and10 is 1

In [ ]:
LILATracts_1And10_is1['Exists_In_WIC'] = LILATracts_1And10_is1['CensusTract'].isin(wic_harris_cnty['CensusTract'])

In [ ]:
LILATracts_1And10_is1['Exists_In_WIC'].value_counts()

False    98
True     22
Name: Exists_In_WIC, dtype: int64

# LA1and10 is 1 and LI is ZERO

In [ ]:
LA1and10_is1_L1_is0['Exists_In_WIC'] = LA1and10_is1_L1_is0['CensusTract'].isin(wic_harris_cnty['CensusTract'])

In [ ]:
LA1and10_is1_L1_is0['Exists_In_WIC'].value_counts()

False    100
True      52
Name: Exists_In_WIC, dtype: int64

# LA1and10 is ZERO and LI is 1

In [ ]:
LA1and10_is0_L1_is1['Exists_In_WIC'] = LA1and10_is0_L1_is1['CensusTract'].isin(wic_harris_cnty['CensusTract'])

In [ ]:
LA1and10_is0_L1_is1['Exists_In_WIC'].value_counts()

False    173
True     123
Name: Exists_In_WIC, dtype: int64

# LA1and10 is ZERO and LI is ZERO

In [ ]:
LA1and10_is0_L1_is0['Exists_In_WIC'] = LA1and10_is0_L1_is0['CensusTract'].isin(wic_harris_cnty['CensusTract'])

In [ ]:
LA1and10_is0_L1_is0['Exists_In_WIC'].value_counts()

False    148
True      70
Name: Exists_In_WIC, dtype: int64

# Combine the two datasets
- To add the features 'LA1and10' and 'LAhalfand10' to the WIC Dataset

In [ ]:
atlas_wic_combined = pd.merge(wic_harris_cnty[['Store Name', 'Store Address', 'City', 'Zip', 'CensusTract',
       'LILA 1 and 10', 'LILA .5 and 10']],
                              df_food_atlas,
                              on = 'CensusTract',
                              how='inner')
atlas_wic_combined

,Store Name,Store Address,City,Zip,CensusTract,LILA 1 and 10,LILA .5 and 10,State,County,Urban,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,AAPEX PHARMACY + DME,1307 W CLAY ST,HOUSTON,77019,48201410200,0.0,0.0,Texas,Harris County,1,...,180.0,3483.0,139.0,248.0,2.0,19.0,311.0,774.0,61.0,0.0
1,ANGEL MEDICAL SUPPLY,5829 W SAM HOUSTON PKY N 1209,HOUSTON,77041,48201540100,0.0,0.0,Texas,Harris County,1,...,838.0,7425.0,652.0,2659.0,4.0,57.0,1552.0,3625.0,72.0,211.0
2,KROGER #396,6350 N ELDRIDGE PKWY,HOUSTON,77041,48201540100,0.0,0.0,Texas,Harris County,1,...,838.0,7425.0,652.0,2659.0,4.0,57.0,1552.0,3625.0,72.0,211.0
3,ARLAN'S #20,31315 FM 2920 STE 20,WALLER,77484,48201556000,0.0,0.0,Texas,Harris County,0,...,454.0,4241.0,816.0,45.0,6.0,71.0,1283.0,2509.0,105.0,259.0
4,ARLAN'S MARKET #2,4614 NASA PARKWAY,SEABROOK,77586,48201341400,0.0,0.0,Texas,Harris County,1,...,800.0,4444.0,179.0,318.0,1.0,18.0,196.0,524.0,27.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,WALMART SUPERCENTER #2724,1107 SOUTH SHAVER STREET,PASADENA,77506,48201322100,0.0,1.0,Texas,Harris County,1,...,245.0,2974.0,57.0,24.0,1.0,39.0,1006.0,3333.0,85.0,322.0
327,WALMART SUPERCENTER #3500,5655 E SAM HOUSTON PKY N,HOUSTON,77015,48201233002,0.0,0.0,Texas,Harris County,1,...,288.0,1722.0,1450.0,149.0,2.0,14.0,595.0,1497.0,13.0,51.0
328,WALMART SUPERCENTER #3584,5405 S RICE AVENUE,HOUSTON,77081,48201421101,0.0,0.0,Texas,Harris County,1,...,88.0,2020.0,560.0,292.0,0.0,18.0,839.0,2276.0,128.0,129.0
329,WALMART SUPERCENTER #5612,2391 S WAYSIDE DRIVE,HOUSTON,77023,48201310700,0.0,1.0,Texas,Harris County,1,...,328.0,2670.0,75.0,46.0,0.0,42.0,1334.0,3454.0,170.0,340.0
330,WATKINS CENTER,10510 CULLEN BLVD,HOUSTON,77047,48201331500,1.0,1.0,Texas,Harris County,1,...,1363.0,636.0,6056.0,66.0,0.0,33.0,354.0,780.0,201.0,555.0

In [ ]:
path = '/content/drive/MyDrive/medschool project/atlas_wic_combined.xlsx'

# Save the Excel file to your Google Drive folder
atlas_wic_combined.to_excel(path)

# Analyze data
- By features 'LILA 1 and 10',	'LILA .5 and 10',	'LA1and10', and	'LAhalfand10'

1) 'LILA 1 and 10' feature
- By count
- Normalized

In [ ]:
atlas_wic_combined['LILA 1 and 10'].value_counts()

0.0    305
1.0     27
Name: LILA 1 and 10, dtype: int64

In [ ]:
round(atlas_wic_combined['LILA 1 and 10'].value_counts(normalize=True),3)

0.0    0.919
1.0    0.081
Name: LILA 1 and 10, dtype: float64

2) LILA .5 and 10
- By count
- Normalized

In [ ]:
atlas_wic_combined['LILA .5 and 10'].value_counts()

0.0    197
1.0    130
Name: LILA .5 and 10, dtype: int64

In [ ]:
atlas_wic_combined[atlas_wic_combined['LILA .5 and 10'].isna()==True]

,County,Store Name,Store Address,City,Zip,CensusTract,LILA 1 and 10,LILA .5 and 10,LA1and10,LAhalfand10
21,HARRIS,EL AHORRO SUPERMARKET #03,5859 BISSONNET,BELLAIRE,77401,48201420900,0.0,NaN,0,1
27,HARRIS,EL AHORRO SUPERMARKET #15,6910 CAPITOL,HOUSTON,77011,48201310900,0.0,NaN,0,0
30,HARRIS,EL AHORRO SUPERMARKET #17,8201 BROADWAY,HOUSTON,77061,48201333100,0.0,NaN,0,0
31,HARRIS,EL AHORRO SUPERMARKET #18,11214 BEECHNUT ST,HOUSTON,77072,48201453000,0.0,NaN,0,0
34,HARRIS,EL RANCHO #31,11210 NORTH FREEWAY,HOUSTON,77037,48201222501,0.0,NaN,0,0

In [ ]:
round(atlas_wic_combined['LILA .5 and 10'].value_counts(normalize=True),3)

0.0    0.602
1.0    0.398
Name: LILA .5 and 10, dtype: float64

3) 'LA1and10' feature
- By count
- Normalized

In [ ]:
atlas_wic_combined['LA1and10'].value_counts()

0    244
1     88
Name: LA1and10, dtype: int64

In [ ]:
round(atlas_wic_combined['LA1and10'].value_counts(normalize=True),3)

0    0.735
1    0.265
Name: LA1and10, dtype: float64

4) 'LAhalfand10' feature
- By count
- Normalized

In [ ]:
atlas_wic_combined['LAhalfand10'].value_counts()

1    259
0     73
Name: LAhalfand10, dtype: int64

In [ ]:
round(atlas_wic_combined['LAhalfand10'].value_counts(normalize=True),3)

1    0.78
0    0.22
Name: LAhalfand10, dtype: float64